module Locators
    class FlightLocator < SitePrism::Page
        # button
        element :tujuanButton, '#formhome > div > div > div.form-flight > div.row.wrapper-form > div.width_228px.list-horizontal__middle.box-flightform.box-flightform__airport.box-flightform__departure > div:nth-child(2) > div.list-horizontal__middle.relative > div.airport.input-flightform'
        element :jakartaTujuanButton, '#formhome > div > div > div.form-flight.z-index-999 > div.row.wrapper-form > div.width_228px.list-horizontal__middle.box-flightform.box-flightform__airport.box-flightform__departure > div:nth-child(2) > div.list-horizontal__middle.relative > div.airport.input-flightform > div > div.auto-body > div > div > ul > li:nth-child(2)'
        element :surabayaTujuanButton, '#formhome > div > div > div.form-flight.z-index-999 > div.row.wrapper-form > div:nth-child(3) > div:nth-child(2) > div.list-horizontal__middle.relative > div.airport.input-flightform > div > div.auto-body > div > div > ul > li:nth-child(3) > div > div > div.col-text > div.text-city'
        element :navRightDateButton, '#formhome > div > div > div.form-flight.z-index-999 > div.row.wrapper-form > div:nth-child(4) > div:nth-child(2) > div:nth-child(2) > div > div > div.widget-datepicker-content > div > div > div:nth-child(1) > div.DayPicker_focusRegion.DayPicker_focusRegion_1 > div.DayPickerNavigation.DayPickerNavigation_1.DayPickerNavigation__horizontal.DayPickerNavigation__horizontal_2 > div.DayPickerNavigation_button.DayPickerNavigation_button_1.DayPickerNavigation_button__horizontal.DayPickerNavigation_button__horizontal_2 > div > span.widget-date-prev-next-logo > i'
        element :date23Button, '#formhome > div > div > div.form-flight.z-index-999 > div.row.wrapper-form > div:nth-child(4) > div:nth-child(2) > div:nth-child(2) > div > div > div.widget-datepicker-content > div > div > div:nth-child(1) > div.DayPicker_focusRegion.DayPicker_focusRegion_1 > div.DayPicker_transitionContainer.DayPicker_transitionContainer_1.DayPicker_transitionContainer__horizontal.DayPicker_transitionContainer__horizontal_2 > div > div:nth-child(2) > div > table > tbody > tr:nth-child(4) > td:nth-child(5) > div'
        element :date25Button, '#formhome > div > div > div.form-flight.z-index-999 > div.row.wrapper-form > div:nth-child(5) > div:nth-child(2) > div:nth-child(2) > div > div > div.widget-datepicker-content > div > div > div:nth-child(1) > div.DayPicker_focusRegion.DayPicker_focusRegion_1 > div.DayPicker_transitionContainer.DayPicker_transitionContainer_1.DayPicker_transitionContainer__horizontal.DayPicker_transitionContainer__horizontal_2 > div > div:nth-child(2) > div > table > tbody > tr:nth-child(4) > td:nth-child(7) > div'
        element :cancelPenumpangMenuButton, '#formhome > div > div > div.form-flight.z-index-999 > div.row.wrapper-form > div.width_228px.list-horizontal__middle.box-flightform.box-flightform__passengerclass > div:nth-child(2) > div > div > div:nth-child(1) > div:nth-child(2) > i'
        element :cariPenerbanganButton, '#formhome > div > div > div.form-flight.z-index-999 > div.row.right > button'
        element :mengertiInformasiButton, '#app > div > div.left-side > div:nth-child(2) > div > div.wrapper-new-search-result > div > div.col-result.list-horizontal__top > div.sort.row > div.col-xs-4.text-sort.right > div:nth-child(2) > div.comp-info-box > div.v3-btn.v3-btn__blue.list-horizontal__middle.btn-action'
        element :okWarningMessageButton, '#ab-iam-ace14aafc00f0e28bd6f1a5975f35482 > div.ab-page-blocker'
        element :transit1Button, '#app > div > div.left-side > div:nth-child(2) > div > div.wrapper-new-search-result > div > div.col-filter.list-horizontal__top > div > form > div > div:nth-child(1) > div > div.list-checkbox > div > div:nth-child(3)'
        element :waktuBerangkat1Button, '#app > div > div.left-side > div:nth-child(2) > div > div.wrapper-new-search-result > div > div.col-filter.list-horizontal__top > div > form > div > div:nth-child(5) > div > div.list-checkbox > div > div:nth-child(2) > div:nth-child(2)'
        element :waktuBerangkat2Button, '#app > div > div.left-side > div:nth-child(2) > div > div.wrapper-new-search-result > div > div.col-filter.list-horizontal__top > div > form > div > div:nth-child(5) > div > div.list-checkbox > div > div:nth-child(2) > div:nth-child(3)'
        element :maskapaiBatikButton, '#app > div > div.left-side > div:nth-child(2) > div > div.wrapper-new-search-result > div > div.col-filter.list-horizontal__top > div > form > div > div:nth-child(7) > div > div.list-checkbox > div > div:nth-child(2)'
        element :maskapaiGarudaButton, '#app > div > div.left-side > div:nth-child(2) > div > div.wrapper-new-search-result > div > div.col-filter.list-horizontal__top > div > form > div > div:nth-child(7) > div > div.list-checkbox > div > div:nth-child(4)'
        element :pilihflightPosition1Button, '#app > div > div.left-side > div:nth-child(2) > div > div.wrapper-new-search-result > div > div.col-result.list-horizontal__top > div.wrapper-result > div > div > div:nth-child(1) > div > div.btn-book-now > div'
        # textfield
        element :minPriceTextfield, '#app > main > div > div.header-search-wrapper > div.filter-bar > div > div > div:nth-child(2) > div:nth-child(3) > div.tix-pop-over.top-bottom.show > div > div.popover-content > div > div.price-textbox-wrap > div:nth-child(1) > input[type=text]'
        element :maxPriceTextfield, '#app > main > div > div.header-search-wrapper > div.filter-bar > div > div > div:nth-child(2) > div:nth-child(3) > div.tix-pop-over.top-bottom.show > div > div.popover-content > div > div.price-textbox-wrap > div:nth-child(3) > input[type=text]'
        # checkbox
        element :pulangCheckbox, '#formhome > div > div > div.form-flight.z-index-999 > div.row.wrapper-form > div:nth-child(5) > div.row.checkbox-flightform'
        # label
        element :fromLabel, '#formhome > div > div > div.form-flight.z-index-999 > div.row.wrapper-form > div.width_228px.list-horizontal__middle.box-flightform.box-flightform__airport.box-flightform__departure > div:nth-child(2) > div.list-horizontal__middle.relative > div.airport.input-flightform > input'
        element :toLabel, '#formhome > div > div > div.form-flight.z-index-999 > div.row.wrapper-form > div:nth-child(3) > div:nth-child(2) > div.list-horizontal__middle.relative > div.airport.input-flightform > input'
        element :flightPosition1Label, '#app > div > div.left-side > div:nth-child(2) > div > div.wrapper-new-search-result > div > div.col-result.list-horizontal__top > div.wrapper-result > div > div > div:nth-child(1)'
        element :flightListLabel, '#app > div > div.left-side > div:nth-child(2) > div > div.wrapper-new-search-result > div > div.col-result.list-horizontal__top > div.wrapper-result'
        element :airlineLabel, '.text-marketing-airline'
        element :warningLabel, '#ab-iam-2396039a7000d438fbdb22a31ad0ff5c > div.ab-in-app-message.ab-background.ab-modal-interactions.ab-modal.ab-centered'
        element :priceLabel, '#app > div > div.left-side > div:nth-child(2) > div > div.wrapper-new-search-result > div > div.col-result.list-horizontal__top > div.wrapper-result > div > div > div:nth-child(1) > div > div.col-xs-6.right.relative > div.row > div.col-xs-7 > div'
    end
end